apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 

namespace: openshfit-compliance 

resources: 
- ../../base

patches: 
  - target: 
      kind: Subscription
      group: operators.coreos.com
      version: v1alpha1
      name: compliance-operator
    path: patch-channel.yaml 